os: linux

dist: xenial

sudo: required

git:
  depth: 3

addons:
  apt:
    update:
    - true

before_install:
  - git clone https://github.com/ZeoRexDevs/gcc_linaro_731_toolchain ~/aarch64-linux-toolchain/
  - sudo chmod -R a+x ~/aarch64-linux-toolchain/*

install: true

script:
  - mkdir out
  - make O=out clean
  - make O=out mrproper
  - export CROSS_COMPILE=~/aarch64-linux-toolchain/bin/aarch64-linux-gnu-
  - export ARCH=arm64 
  - export KBUILD_BUILD_USER="fr3aky"
  - export KBUILD_BUILD_HOST="Phantom_Zone"
  - export ARCH_MTK_PLATFORM=mt6735
  - make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE cp_n3lite_defconfig
  - make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j16
  - KERNEL_DIR=$PWD
  - ZIMAGE=$KERNEL_DIR/out/arch/arm64/boot/*Image*

after_success:
  - cd $KERNEL_DIR/out
  - curl --upload-file arch/arm64/boot/Image.gz https://transfer.sh/mad-oreo-kernel-zImage

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken"
  file_glob: true
  file: $KERNEL_DIR/out/arch/arm64/boot/*Image*
  on:
    tags: false
    repo: ZeoRexDevs/android_kernel_coolpad_note3
    branch: o-8.1.0

branches:
  except:
    - /^(?i:untagged)-.*$/
